<a href="https://colab.research.google.com/github/CrestwoodCustomSolutions/Crestwood-PythonClass/blob/main/Level_10_Part_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Indexing and Slicing - Accessing Array Elements in NumPy

## Introduction


---

## Part 1: Basic Indexing









In [ ]:
import numpy as np

In [ ]:
exam_scores = np.array([90, 85, 77, 92])

In [ ]:
print("First student's score is: ", exam_scores[0])

First student's score is:  90


## Part 2: Multidimensional Indexing
    - Accessing elements in 2D and 3D arrays.
    - Using row and column indices.


In [ ]:
sales_data = np.array([
    [[200, 222], 220, 250],
    [210, 230, 275],
    [190, 205, 235]
])

<ipython-input-9-be08a371c6c6>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  sales_data = np.array([


In [ ]:
sales_data[0, 0][1]

222

## Part 3: Basic Slicing
    - How to slice arrays to get subarrays.
    - Using the `start:stop:step` notation.


In [ ]:
monthly_revenue = np.array([200, 220, 250, 275, 344, 350, 320, 400, 420, 450, 450])

In [ ]:
monthly_revenue[1:5]
monthly_revenue[::2]
monthly_revenue[::-1]

array([450, 450, 420, 400, 320, 350, 344, 275, 250, 220, 200])

## Part 4: Advanced Slicing Techniques
    - Using boolean arrays for indexing.
    - Combining slicing with conditional statements.


In [ ]:
avg = np.mean(monthly_revenue)
avg

334.45454545454544

In [ ]:
monthly_revenue > avg

array([False, False, False, False,  True,  True, False,  True,  True,
        True,  True])

In [ ]:
monthly_revenue[monthly_revenue > avg]

array([344, 350, 400, 420, 450, 450])

## Part 5: Important Caveats and Best Practices
    - Mention that slices are views, not copies.
    - The importance of being aware of data types when slicing and indexing.


In [ ]:
monthly_revenue_ab_avg = monthly_revenue[monthly_revenue > avg]

In [ ]:
monthly_revenue_ab_avg

array([344, 350, 400, 420, 450, 450])