<a href="https://colab.research.google.com/github/CrestwoodCustomSolutions/Crestwood-PythonClass/blob/main/Level_10_Part_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mini Project: 1D Slicing and Indexing with NumPy

## Objective

In this mini-project, you will practice 1D slicing and indexing techniques using NumPy. We'll work on a dataset that represents monthly sales data for a retail store and perform various data manipulation tasks.

## Dataset

Let's assume we have a 1D NumPy array that represents the monthly sales for a retail store for one year, in thousands of dollars.



In [1]:
import numpy as np

monthly_sales = np.array([200, 220, 250, 275, 300, 320, 350, 370, 400, 420, 450, 475])


## Tasks

### Task 1: Basic Indexing

1. Access and print the sales data for January (the first month).
2. Access and print the sales data for December (the last month).








In [2]:
print("January info: ", monthly_sales[0])
print("December info: ", monthly_sales[-1])

January info:  200
December info:  475


### Task 2: Access Quarterly Data

1. Extract and print the sales data for each quarter (Q1, Q2, Q3, and Q4).

In [3]:
q1s = monthly_sales[:3]
q2s = monthly_sales[3:6]
q3s = monthly_sales[6:9]
q4s = monthly_sales[9:]

print(np.mean(q1s))
print(q2s)
print(q3s)
print(q4s)

223.33333333333334
[275 300 320]
[350 370 400]
[420 450 475]


### Task 3: Modify Sales Data

1. Assume that there was an error in the data entry for the month of April. The correct sales figure is $280,000. Update this value in the array.
2. Print the updated array to confirm the change.

In [ ]:
monthly_sales[3] = 280
print(monthly_sales)

[200 220 250 280 300 320 350 370 400 420 450 475]


### Task 4: Summer Sales

1. Extract and print the sales data for the summer months (June, July, August).
2. Calculate and print the average sales for the summer months.

In [ ]:
summer_m = monthly_sales[5:8]
print(summer_m)

avg_summer = np.mean(summer_m)
print(avg_summer)

[320 350 370]
346.6666666666667


### Task 5: Above Average Months

1. Calculate the average monthly sales for the entire year.
2. Identify and print the months where the sales were above average.

In [ ]:
avg = np.mean(monthly_sales)

In [ ]:
monthly_sales[monthly_sales > avg]

array([350, 370, 400, 420, 450, 475])